name: sip_calculator
description: SIP & Lump-sum Calculator

publish_to: 'none'

version: 4.1.0+19

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  velocity_x: ^4.3.1
  share_plus: ^9.0.0
  in_app_review: ^2.0.12
  google_mobile_ads: ^5.3.1
  fl_chart: ^0.69.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true

  fonts:
    - family: IBM Plex Mono
      fonts:
        - asset: assets/fonts/IBM_Plex_Mono/IBMPlexMono-Regular.ttf
        - asset: assets/fonts/IBM_Plex_Mono/IBMPlexMono-Italic.ttf
          style: italic
        - asset: assets/fonts/IBM_Plex_Mono/IBMPlexMono-Bold.ttf
          weight: 700
